feastmode/urls.py
#feastmode/urls.py
"""
URL configuration for feastmode project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
# main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('accounts/signin/', views.Signin.as_view(), name='signin'),
    path('accounts/signup/', views.signup, name='signup'),
    path('parties/', views.party_index, name='party-index'),
    path('parties/create/', views.PartyCreate.as_view(), name='party-create'),
    path('parties/find/', views.party_find, name='party-find'),
    path('parties/<str:invite_id>/', views.party_detail, name='party-detail'),
    path('parties/<str:invite_id>/update/', views.PartyUpdate.as_view(), name='party-update'),
    path('parties/<str:invite_id>/add-rsvp/', views.add_rsvp, name='add-rsvp'),
    path('parties/<str:invite_id>/dishes/<int:dish_id>/', views.dish_detail, name='dish-detail'),
    path('parties/<str:invite_id>/dishes/create/', views.DishCreate.as_view(), name='dish-create'),
    path('parties/<str:invite_id>/dishes/<int:pk>/update/', views.DishUpdate.as_view(), name='dish-update'),
    path('parties/<str:invite_id>/dishes/<int:pk>/delete/', views.DishDelete.as_view(), name='dish-delete'),
] 

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
from django.urls import reverse

RSVP_STATUS = (
  ('I', 'Invited'),
  ('A', 'Attending'),
  ('N', 'Not attending'),
  ('M', 'Maybe')
)

DISH_CATEGORY = (
  ('A', 'Appetizer'),
  ('M', 'Main'),
  ('S', 'Side'),
  ('D', 'Dessert'),
  ('B', 'Beverage')
)

PARTY_STATUS = (
  ('A', 'Active'),
  ('C', 'Cancelled')
)

class Party(models.Model):
  name = models.CharField(max_length=100)
  owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
  invite_id = models.CharField(max_length=6, unique=True, blank=True, null=True)
  time = models.DateTimeField()
  location = models.CharField(max_length=150)
  dresscode = models.CharField(max_length=100)
  status = models.CharField(
    max_length=1,
    choices=PARTY_STATUS,
    default=PARTY_STATUS[0][0],
  )

  def save(self, *args, **kwargs):
    if not self.invite_id:
      self.invite_id = str(uuid4())[:6]
      
    super().save(*args, **kwargs)

  def __str__(self):
    return f"{self.name}"
  
  def get_absolute_url(self):
    return reverse('party-detail', kwargs={ 'invite_id': self.invite_id })

class Rsvp(models.Model):
  party = models.ForeignKey(Party, on_delete=models.CASCADE)
  status = models.CharField(
    max_length=1,
    choices=RSVP_STATUS,
    default=RSVP_STATUS[0][0],
  )
  user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

  def __str__(self):
    return f"{self.status} - {self.user.username} - {self.party.invite_id}"
  
class Dish(models.Model):
  party = models.ForeignKey(Party, on_delete=models.CASCADE)
  name = models.CharField(max_length=100)
  img_url = models.URLField(max_length=300, verbose_name='Image URL', null=True,)
  description = models.TextField(max_length=500)
  category = models.CharField(
    max_length=1,
    choices=DISH_CATEGORY,
    default=DISH_CATEGORY[0][0],
  )
  claimed_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

  def __str__(self):
    return f"{self.name}"

main_app/forms.py
from django import forms
from .models import Rsvp, Party
from django.forms import DateTimeInput
from django.contrib.auth.forms import UserCreationForm

class RsvpForm(forms.ModelForm):
    class Meta:
        model = Rsvp
        fields = ['status']

class PartyForm(forms.ModelForm):
    class Meta:
        model = Party
        fields = ['name', 'time', 'location', 'dresscode']
        widgets = {
            'time': forms.DateTimeInput(
            # format=('%Y-%m-%d %H:%M'),
            attrs={
                'placeholder': 'Select a date',
                'type': 'datetime-local'
            }
        )
    }

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required. 30 characters or fewer. Letters only.')
    last_name = forms.CharField(max_length=150, required=True, help_text='Required. 150 characters or fewer. Letters only.')
    email = forms.EmailField(required=True, help_text='Required. Letters, digits and @/./+/-/_ only.')

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from django.urls import reverse
from main_app.models import Party, Rsvp, Dish
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RsvpForm, PartyForm, CustomUserCreationForm
from .helpers import get_rsvp
from .models import DISH_CATEGORY

# Create your views here.

class Home(LoginView):
    template_name = 'home.html'

class Signin(LoginView):
    template_name = 'signin.html'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = CustomUserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

@login_required
def party_index(request):
    parties = Party.objects.filter(rsvp__user_id=request.user.id)
    
    upcoming_parties = [p for p in parties if p.time >= timezone.now()]
    past_parties = [p for p in parties if p.time < timezone.now()]

    return render(request, 'parties/index.html', { 
        'upcoming_parties': upcoming_parties, 
        'past_parties': past_parties 
    })

def party_detail(request, invite_id):
    party = Party.objects.get(invite_id=invite_id)
    if request.user:
        rsvp = get_rsvp(party, request.user.id) 
    
    rsvp_form = RsvpForm(initial={ 'status': rsvp.status } if rsvp else {})
    return render(request, 'parties/party-detail.html', { 'party': party, 'rsvp_form': rsvp_form })

class PartyCreate(LoginRequiredMixin, CreateView):
    model = Party
    form_class = PartyForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        response = super().form_valid(form)
        Rsvp.objects.create(user=self.request.user, party=form.instance, status='A')
        return response

class PartyUpdate(LoginRequiredMixin, UpdateView):
    model = Party
    fields = ['name', 'time', 'location', 'dresscode', 'status']

    def get_object(self, queryset=None):
        return Party.objects.get(invite_id=self.kwargs.get('invite_id'))
    
def party_find(request):
    invite_id = request.GET.get('invite_id')
    return redirect('party-detail', invite_id=invite_id)

@login_required
def add_rsvp(request, invite_id):
    rsvp_form = RsvpForm(request.POST)
    if rsvp_form.is_valid():
        party = Party.objects.get(invite_id=invite_id)
        existing_rsvp = get_rsvp(party, request.user.id)
        if existing_rsvp:
            existing_rsvp.status = rsvp_form.cleaned_data['status']
            existing_rsvp.save()
        else:
            new_rsvp = rsvp_form.save(commit=False)
            new_rsvp.user_id = request.user.id
            new_rsvp.party_id = party.id
            new_rsvp.save()

    return redirect('party-detail', invite_id=invite_id)

class DishCreate(LoginRequiredMixin, CreateView):
    model = Dish
    fields = ['name', 'img_url', 'description', 'category', 'claimed_by']

    def dispatch(self, request, *args, **kwargs):
        self.party = Party.objects.get(invite_id=kwargs['invite_id'])
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        form.instance.party = self.party
        if not form.cleaned_data.get('img_url'):
            form.instance.img_url = 'https://i.imgur.com/MDp9VvT.png'
        if self.request.user.id == self.party.owner.id and not form.cleaned_data.get('claimed_by'):
            form.instance.claimed_by = None
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['img_url'].required = False
        if self.request.user.id == self.party.owner.id:
            form.fields['claimed_by'].required = False
            form.fields['claimed_by'].queryset = User.objects.filter(rsvp__party__invite_id=self.party.invite_id)
        else:
            form.fields['claimed_by'].empty_label = None
            form.fields['claimed_by'].queryset = User.objects.filter(id=self.request.user.id)
        return form
    
    def get_success_url(self, **kwargs):
        invite_id = self.kwargs.get('invite_id')
        return reverse('party-detail', kwargs={ 'invite_id': invite_id })

class DishUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Dish
    fields = '__all__'

    def dispatch(self, request, *args, **kwargs):
        self.dish = self.get_object()
        self.party = Party.objects.get(invite_id=kwargs['invite_id'])
        return super().dispatch(request, *args, **kwargs)
    
    def test_func(self):
        if self.request.user.id == self.party.owner.id:
            return True
        if self.dish.claimed_by == None:
            return True
        return self.request.user.id == self.dish.claimed_by.id
    
    def handle_no_permission(self):
        invite_id = self.party.invite_id
        messages.error(self.request, "Sorry! You can't edit other guests dishes!")
        return redirect('party-detail', invite_id= invite_id)    
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['img_url'].required = False
        if self.request.user.id == self.party.owner.id:
            form.fields['claimed_by'].required = False
            form.fields['claimed_by'].queryset = User.objects.filter(rsvp__party__invite_id=self.party.invite_id)
        else:
            form.fields['claimed_by'].queryset = User.objects.filter(id=self.request.user.id)
        return form
    
    def form_valid(self, form):
        if not form.cleaned_data.get('img_url'):
            form.instance.img_url = 'https://i.imgur.com/MDp9VvT.png'
        return super().form_valid(form)
    
    
    def get_success_url(self, **kwargs):
        invite_id = self.kwargs.get('invite_id')
        return reverse('party-detail', kwargs={ 'invite_id': invite_id })

class DishDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Dish
    
    def dispatch(self, request, *args, **kwargs):
        self.dish = self.get_object()
        self.party = self.dish.party
        self.invite_id = kwargs['invite_id']
        return super().dispatch(request, *args, **kwargs)
    
    def test_func(self):
        dish = self.get_object()
        return self.request.user.id == dish.party.owner.id or self.request.user.id == dish.claimed_by.id
    
    def handle_no_permission(self):
        messages.error(self.request, "Sorry! You can't delete other guests dishes!")
        return redirect('party-detail', invite_id=self.invite_id)
    
    def get_success_url(self, **kwargs):
        return reverse('party-detail', kwargs={ 'invite_id': self.invite_id })
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['party'] = self.object.party
        return context

def dish_detail(request, dish_id, invite_id):
    dish = Dish.objects.get(id=dish_id)
    party = Party.objects.get(invite_id=invite_id)
    return render(request, 'parties/dish-detail.html', { 'dish': dish, 'party': party })

main_app/templates/parties/dish-detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/dish-detail.css' %}" />
{% endblock %} {% block content %}
<section class="flex-column">
  <h1>{{ dish.name }}</h1>
  <img src="{{dish.img_url}}" class="dish-img" />
  <div class="dish-txt">
    <p>Dish name:</p>
    {{ dish.description }}
    <p>Category:</p>
    {{ dish.get_category_display }}
    <p>Claimed by:</p>
    {{ dish.claimed_by }}
    <div class="flex-row edit">
      {% if dish.claimed_by.id == user.id or party.owner.id == user.id %}
        <a href="{% url "dish-update" party.invite_id dish.id %}"><img src="{% static '../static/images/edit.svg' %}"></a>
        <a href="{% url "dish-delete" party.invite_id dish.id %}"><img src="{% static '../static/images/delete.svg' %}"></a>
      {% endif %}
    </div>
  </div>
</section>

{% endblock %}

main_app/templates/parties/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
    <link rel="stylesheet" href="{% static 'css/party-index.css' %}">
{% endblock %} 
{% block content %}
    <div class="flex-column">
        <section class="party-index-title">
            <h1>💃  My Parties🕺</h1>
            <a href="{% url "party-create" %}" class="btn">Create a Party!</a>
        </section>
        <section class="party-index-sub-container">
            {% include 'parties/party-list.html' with title='Upcoming Parties' parties=upcoming_parties %}
        </section>
        <section class="party-index-sub-container">
            {% include 'parties/party-list.html' with title='Past Parties' parties=past_parties %}
        </section>
    </div>
{% endblock %}

main_app/templates/parties/party-detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
    <link rel="stylesheet" href="{% static 'css/party-detail.css' %}">
{% endblock %} 
{% block content %}
    <div class="party-detail-container">
        <section class="party-detail-title">
            <h1>{{ party.name }}</h1>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert">
                        {{ message }}
                     </div>
                {% endfor %}
            {% endif %}
        </section>
        {% if party.status == 'C' %}
            <section class="party-detail-sub-container cancel">
                <h1>SORRY!</h1>
                <p>We regret to inform you that this party has been cancelled.</p>
            </section>    
        {% endif%}
        <section class="party-detail-sub-container">
            <h1>Information</h1>
            <p>When | {{party.time}}</p>
            <p>Where | {{party.location}}</p>
            <p>Wear | {{party.dresscode}}</p>
            {% if party.owner.id == user.id %}
                <div class="divider">
                    <hr>
                </div>
                <p>Invitation Code: {{party.invite_id}}</p>
                <a href ="{% url 'party-update' party.invite_id%}" class="btn">Edit Party</a>
            {% elif user.is_authenticated %}
                <form
                    action="{% url 'add-rsvp' party.invite_id %}"
                    method="POST"
                    autocomplete="off"
                >
                    {% csrf_token %}
                    {{ rsvp_form.as_table }}
                    <button type="submit" class="btn submit">RSVP</button>
            <form>
            {% else %}
                <div class="not-logged">
                    <p>Not logged in? Don't have an account?</p>
                    <div class="flex-row gap">
                        <a href="{% url "signin" %}" class="btn">Log In</a>
                        <a href="{% url "signup" %}" class="btn">Sign Up</a>
                    </div>
                </div>
            {% endif %}
        </section>
        <section class="party-detail-sub-container">
            <h1>RSVPs</h1>
            <ul>
                {% for rsvp in party.rsvp_set.all %}
                    {% if rsvp.user.id == party.owner.id %}
                        <li><i>Hosted by - {{ rsvp.user.username}}</i></li>
                    {% else %}
                    <li> {{ rsvp.user.username }} ({{ rsvp.get_status_display }})</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </section>
        <section class="dish-detail-sub-container dishes-section">
            <h1>Dishes</h1>
            <div class="dishes-wrapper">
                {% for dish in party.dish_set.all %}
                    <div class="dish-container">
                        <div class="dish-img-wrapper">
                            <a href="{% url "dish-detail" party.invite_id dish.id %}"><img src="{{ dish.img_url }}" class="dish-img"></a>
                        </div>
                        <a href="{% url "dish-detail" party.invite_id dish.id %}">{{ dish.name }}</a>
                        {% if dish.claimed_by == None %}
                            <p>This dish hasn't been claimed yet!</p>
                        {% else %}
                            <p>This dish was claimed by: {{ dish.claimed_by }}</p>
                        {% endif %}
                        <div class="dish-container-edit">
                            {% if dish.claimed_by.id == user.id or party.owner.id == user.id or dish.claimed_by == None %}
                                <a href="{% url "dish-update" party.invite_id dish.id %}"><img src="{% static '../static/images/edit.svg' %}"></a>
                            {% endif %}
                            {% if dish.claimed_by.id == user.id or party.owner.id == user.id %}
                                <a href="{% url "dish-delete" party.invite_id dish.id %}"><img src="{% static '../static/images/delete.svg' %}"></a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a href="{% url "dish-create" party.invite_id %}" class="btn">Add a new dish</a>
        </section>
    </div>
{% endblock %}

main_app/templates/parties/party-list.html
<section>
    <h1>{{ title }}</h1>
    {% for party in parties %}
    <p><a href="{% url 'party-detail' party.invite_id %}">{{ party.name }} | {{party.time}}</a></p>
    {% endfor %}
</section>